// ─── Minimal PDF Generator ────────────────────────────────────────────────────
// Generates a simple human-readable PDF from structured data.
// This is a POC-level implementation — not production quality.
// In F2, this moves to packages/sdf-kit/src/producer/pdf.ts with
// proper template support (pdf-lib + pdfkit for complex layouts).
//
// SDF_FORMAT.md Section 4.3:
//   - visual.pdf MUST be PDF 1.4 or later
//   - All resources MUST be embedded (no external URLs)
//   - MUST NOT embed executable content

import { PDFDocument, StandardFonts, rgb, type PDFPage } from 'pdf-lib';
import { SDFMeta } from './types.js';

export interface PDFGeneratorOptions {
  meta: SDFMeta;
  data: Record<string, unknown>;
}

export async function generatePDF(options: PDFGeneratorOptions): Promise<Buffer> {
  const { meta, data } = options;

  const doc  = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const mono = await doc.embedFont(StandardFonts.Courier);

  const page = doc.addPage([595.28, 841.89]); // A4

  const renderer = new PageRenderer(page, font, bold, mono);
  renderer.renderDocument(meta, data);

  const pdfBytes = await doc.save();
  return Buffer.from(pdfBytes);
}

// ─── Page Renderer ────────────────────────────────────────────────────────────

class PageRenderer {
  private y: number;
  private readonly margin   = 56;
  private readonly pageWidth = 595.28;
  private readonly maxWidth:  number;

  constructor(
    private readonly page: PDFPage,
    private readonly font: ReturnType<PDFDocument['embedFont']> extends Promise<infer T> ? T : never,
    private readonly bold: ReturnType<PDFDocument['embedFont']> extends Promise<infer T> ? T : never,
    private readonly mono: ReturnType<PDFDocument['embedFont']> extends Promise<infer T> ? T : never,
  ) {
    this.y = 841.89 - this.margin;
    this.maxWidth = this.pageWidth - this.margin * 2;
  }

  renderDocument(meta: SDFMeta, data: Record<string, unknown>): void {
    // Header bar
    this.page.drawRectangle({
      x: 0, y: 841.89 - 60,
      width: this.pageWidth, height: 60,
      color: rgb(0.10, 0.09, 0.36),
    });
    this.page.drawText('SDF — Smart Document Format', {
      x: this.margin, y: 841.89 - 38,
      size: 16, font: this.bold, color: rgb(1, 1, 1),
    });
    this.page.drawText(`v${meta.sdf_version}  ·  ${meta.document_type ?? 'document'}`, {
      x: this.margin, y: 841.89 - 54,
      size: 9, font: this.font, color: rgb(0.8, 0.8, 0.9),
    });

    this.y = 841.89 - 80;

    // Meta section
    this.sectionTitle('Document Identity');
    this.keyValue('Document ID',   meta.document_id);
    this.keyValue('Issuer',        meta.issuer + (meta.issuer_id ? ` (${meta.issuer_id})` : ''));
    if (meta.recipient) this.keyValue('Recipient', meta.recipient + (meta.recipient_id ? ` (${meta.recipient_id})` : ''));
    this.keyValue('Created',       meta.created_at);
    if (meta.document_type)    this.keyValue('Document type',    meta.document_type);
    if (meta.document_version) this.keyValue('Document version', meta.document_version);

    this.spacer();

    // Data section
    this.sectionTitle('Document Data');
    this.renderObject(data, 0);

    // Footer
    this.page.drawLine({
      start: { x: this.margin, y: 36 },
      end:   { x: this.pageWidth - this.margin, y: 36 },
      thickness: 0.5,
      color: rgb(0.7, 0.7, 0.7),
    });
    this.page.drawText(
      `SDF ${meta.sdf_version}  ·  ${meta.document_id}  ·  Generated by Etapsky SDF POC`,
      { x: this.margin, y: 22, size: 7, font: this.font, color: rgb(0.6, 0.6, 0.6) },
    );
    this.page.drawText(
      'This document contains a machine-readable data layer. Open with an SDF-aware reader to access structured data.',
      { x: this.margin, y: 12, size: 7, font: this.font, color: rgb(0.6, 0.6, 0.6) },
    );
  }

  private sectionTitle(title: string): void {
    this.y -= 4;
    this.page.drawRectangle({
      x: this.margin, y: this.y - 2,
      width: this.maxWidth, height: 18,
      color: rgb(0.94, 0.93, 0.99),
    });
    this.page.drawText(title.toUpperCase(), {
      x: this.margin + 6, y: this.y + 2,
      size: 8, font: this.bold,
      color: rgb(0.20, 0.18, 0.55),
    });
    this.y -= 22;
  }

  private keyValue(key: string, value: string): void {
    if (this.y < 60) return; // clip — POC does not handle multi-page
    this.page.drawText(key, {
      x: this.margin, y: this.y,
      size: 9, font: this.bold, color: rgb(0.3, 0.3, 0.3),
    });
    this.page.drawText(String(value), {
      x: this.margin + 140, y: this.y,
      size: 9, font: this.font, color: rgb(0.1, 0.1, 0.1),
      maxWidth: this.maxWidth - 140,
    });
    this.y -= 14;
  }

  private spacer(): void {
    this.y -= 8;
  }

  private renderObject(obj: Record<string, unknown>, depth: number): void {
    const indent = depth * 12;
    for (const [key, value] of Object.entries(obj)) {
      if (this.y < 60) break;
      if (value === null || value === undefined) continue;

      if (typeof value === 'object' && !Array.isArray(value)) {
        // Nested object — print key as sub-header
        this.page.drawText(this.formatKey(key), {
          x: this.margin + indent, y: this.y,
          size: 9, font: this.bold, color: rgb(0.25, 0.25, 0.25),
        });
        this.y -= 13;
        this.renderObject(value as Record<string, unknown>, depth + 1);
      } else if (Array.isArray(value)) {
        this.page.drawText(this.formatKey(key), {
          x: this.margin + indent, y: this.y,
          size: 9, font: this.bold, color: rgb(0.25, 0.25, 0.25),
        });
        this.y -= 13;
        value.forEach((item, i) => {
          if (this.y < 60) return;
          if (typeof item === 'object' && item !== null) {
            this.page.drawText(`[${i + 1}]`, {
              x: this.margin + indent + 8, y: this.y,
              size: 8, font: this.bold, color: rgb(0.4, 0.4, 0.4),
            });
            this.y -= 12;
            this.renderObject(item as Record<string, unknown>, depth + 2);
          } else {
            this.keyValue(`  [${i + 1}]`, String(item));
          }
        });
      } else {
        // Primitive
        if (this.y < 60) break;
        this.page.drawText(this.formatKey(key), {
          x: this.margin + indent, y: this.y,
          size: 9, font: this.bold, color: rgb(0.3, 0.3, 0.3),
        });
        this.page.drawText(String(value), {
          x: this.margin + indent + 140, y: this.y,
          size: 9, font: this.font, color: rgb(0.1, 0.1, 0.1),
          maxWidth: this.maxWidth - indent - 140,
        });
        this.y -= 13;
      }
    }
  }

  private formatKey(key: string): string {
    return key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  }
}